name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: 'latest'
          project_id: <your-project-id>
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: 'latest'
        env:
          PROJECT_ID: <your-project-id>

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/<your-project-id>/<image-name>

      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
